before_script:
- apt-get install
- pip install -U tox twine wheel codecov

only:
- tags
- /^issue-.*$/
- web

test:2.7:
    image: python:2.7
    script:
    - tox

test:3.6:
    image: python:3.6
    script:
    - tox
